import { api, z, postgres } from "@superblocksteam/sdk-api";

const APPS_DB = "c6e32cf4-ca66-42ae-aeb3-58c84ffae574";

// Top 200 players from 2024-25 ADP (Fantasy Pros consensus)
const ADP_2024: Array<[string, string, string, number]> = [
  // [name, position, team, rank]
  ["Christian McCaffrey", "RB", "SF", 1],
  ["CeeDee Lamb", "WR", "DAL", 2],
  ["Tyreek Hill", "WR", "MIA", 3],
  ["Bijan Robinson", "RB", "ATL", 4],
  ["Breece Hall", "RB", "NYJ", 5],
  ["Amon-Ra St. Brown", "WR", "DET", 6],
  ["Ja'Marr Chase", "WR", "CIN", 7],
  ["Justin Jefferson", "WR", "MIN", 8],
  ["Saquon Barkley", "RB", "PHI", 9],
  ["Garrett Wilson", "WR", "NYJ", 10],
  ["Puka Nacua", "WR", "LAR", 11],
  ["A.J. Brown", "WR", "PHI", 12],
  ["Jonathan Taylor", "RB", "IND", 13],
  ["Jahmyr Gibbs", "RB", "DET", 14],
  ["Travis Kelce", "TE", "KC", 15],
  ["Kyren Williams", "RB", "LAR", 16],
  ["De'Von Achane", "RB", "MIA", 17],
  ["Drake London", "WR", "ATL", 18],
  ["Davante Adams", "WR", "LV", 19],
  ["Mike Evans", "WR", "TB", 20],
  ["Chris Olave", "WR", "NO", 21],
  ["Derrick Henry", "RB", "BAL", 22],
  ["Sam LaPorta", "TE", "DET", 23],
  ["Josh Allen", "QB", "BUF", 24],
  ["Nico Collins", "WR", "HOU", 25],
  ["Marvin Harrison Jr.", "WR", "ARI", 26],
  ["Deebo Samuel", "WR", "SF", 27],
  ["James Cook", "RB", "BUF", 28],
  ["Isiah Pacheco", "RB", "KC", 29],
  ["DK Metcalf", "WR", "SEA", 30],
  ["Patrick Mahomes", "QB", "KC", 31],
  ["Jalen Hurts", "QB", "PHI", 32],
  ["D.J. Moore", "WR", "CHI", 33],
  ["Brandon Aiyuk", "WR", "SF", 34],
  ["Kenneth Walker III", "RB", "SEA", 35],
  ["Travis Etienne Jr.", "RB", "JAX", 36],
  ["Josh Jacobs", "RB", "GB", 37],
  ["Aaron Jones", "RB", "MIN", 38],
  ["Mark Andrews", "TE", "BAL", 39],
  ["Lamar Jackson", "QB", "BAL", 40],
  ["Jaylen Waddle", "WR", "MIA", 41],
  ["Rashee Rice", "WR", "KC", 42],
  ["Zay Flowers", "WR", "BAL", 43],
  ["Michael Pittman Jr.", "WR", "IND", 44],
  ["Tank Dell", "WR", "HOU", 45],
  ["Tee Higgins", "WR", "CIN", 46],
  ["Joe Mixon", "RB", "HOU", 47],
  ["Terry McLaurin", "WR", "WAS", 48],
  ["George Pickens", "WR", "PIT", 49],
  ["Stefon Diggs", "WR", "HOU", 50],
  ["Christian Kirk", "WR", "JAX", 51],
  ["Rhamondre Stevenson", "RB", "NE", 52],
  ["DeVonta Smith", "WR", "PHI", 53],
  ["Raheem Mostert", "RB", "MIA", 54],
  ["Tony Pollard", "RB", "TEN", 55],
  ["Rachaad White", "RB", "TB", 56],
  ["Brock Bowers", "TE", "LV", 57],
  ["Dalton Kincaid", "TE", "BUF", 58],
  ["David Njoku", "TE", "CLE", 59],
  ["C.J. Stroud", "QB", "HOU", 60],
  ["Malik Nabers", "WR", "NYG", 61],
  ["Rome Odunze", "WR", "CHI", 62],
  ["Jonathon Brooks", "RB", "CAR", 63],
  ["Keenan Allen", "WR", "CHI", 64],
  ["Anthony Richardson", "QB", "IND", 65],
  ["Diontae Johnson", "WR", "CAR", 66],
  ["Calvin Ridley", "WR", "TEN", 67],
  ["Brian Thomas Jr.", "WR", "JAX", 68],
  ["Zamir White", "RB", "LV", 69],
  ["Kyler Murray", "QB", "ARI", 70],
  ["Jordan Addison", "WR", "MIN", 71],
  ["Najee Harris", "RB", "PIT", 72],
  ["Jaylen Warren", "RB", "PIT", 73],
  ["Courtland Sutton", "WR", "DEN", 74],
  ["Jake Ferguson", "TE", "DAL", 75],
  ["Trey McBride", "TE", "ARI", 76],
  ["Dak Prescott", "QB", "DAL", 77],
  ["Joe Burrow", "QB", "CIN", 78],
  ["Amari Cooper", "WR", "CLE", 79],
  ["Alvin Kamara", "RB", "NO", 80],
  ["Rashid Shaheed", "WR", "NO", 81],
  ["Xavier Worthy", "WR", "KC", 82],
  ["D'Andre Swift", "RB", "CHI", 83],
  ["Javonte Williams", "RB", "DEN", 84],
  ["Tyler Lockett", "WR", "SEA", 85],
  ["Nick Chubb", "RB", "CLE", 86],
  ["Zack Moss", "RB", "CIN", 87],
  ["Jayden Daniels", "QB", "WAS", 88],
  ["Caleb Williams", "QB", "CHI", 89],
  ["Devin Singletary", "RB", "NYG", 90],
  ["Cooper Kupp", "WR", "LAR", 91],
  ["David Montgomery", "RB", "DET", 92],
  ["Chase Brown", "RB", "CIN", 93],
  ["Brian Robinson Jr.", "RB", "WAS", 94],
  ["James Conner", "RB", "ARI", 95],
  ["Keon Coleman", "WR", "BUF", 96],
  ["Ladd McConkey", "WR", "LAC", 97],
  ["Curtis Samuel", "WR", "BUF", 98],
  ["Josh Downs", "WR", "IND", 99],
  ["Evan Engram", "TE", "JAX", 100],
  ["George Kittle", "TE", "SF", 101],
  ["T.J. Hockenson", "TE", "MIN", 102],
  ["Dallas Goedert", "TE", "PHI", 103],
  ["Pat Freiermuth", "TE", "PIT", 104],
  ["Jerome Ford", "RB", "CLE", 105],
  ["Tyler Allgeier", "RB", "ATL", 106],
  ["Gus Edwards", "RB", "LAC", 107],
  ["Rico Dowdle", "RB", "DAL", 108],
  ["Chuba Hubbard", "RB", "CAR", 109],
  ["Jaxon Smith-Njigba", "WR", "SEA", 110],
  ["Chris Godwin", "WR", "TB", 111],
  ["Darnell Mooney", "WR", "ATL", 112],
  ["Joshua Palmer", "WR", "LAC", 113],
  ["Wan'Dale Robinson", "WR", "NYG", 114],
  ["Adam Thielen", "WR", "CAR", 115],
  ["Romeo Doubs", "WR", "GB", 116],
  ["Jayden Reed", "WR", "GB", 117],
  ["Christian Watson", "WR", "GB", 118],
  ["Jalen Tolbert", "WR", "DAL", 119],
  ["Quentin Johnston", "WR", "LAC", 120],
];

// Top 200 players from 2025-26 ADP (Fantasy Pros consensus)
const ADP_2025: Array<[string, string, string, number]> = [
  ["Ja'Marr Chase", "WR", "CIN", 1],
  ["Bijan Robinson", "RB", "ATL", 2],
  ["Saquon Barkley", "RB", "PHI", 3],
  ["Jahmyr Gibbs", "RB", "DET", 4],
  ["CeeDee Lamb", "WR", "DAL", 5],
  ["Justin Jefferson", "WR", "MIN", 6],
  ["Christian McCaffrey", "RB", "SF", 7],
  ["Malik Nabers", "WR", "NYG", 8],
  ["Amon-Ra St. Brown", "WR", "DET", 9],
  ["De'Von Achane", "RB", "MIA", 10],
  ["Josh Allen", "QB", "BUF", 11],
  ["Lamar Jackson", "QB", "BAL", 12],
  ["Drake London", "WR", "ATL", 13],
  ["Brock Bowers", "TE", "LV", 14],
  ["A.J. Brown", "WR", "PHI", 15],
  ["Derrick Henry", "RB", "BAL", 16],
  ["Puka Nacua", "WR", "LAR", 17],
  ["Nico Collins", "WR", "HOU", 18],
  ["Brian Thomas Jr.", "WR", "JAX", 19],
  ["Breece Hall", "RB", "NYJ", 20],
  ["Jonathan Taylor", "RB", "IND", 21],
  ["Jalen Hurts", "QB", "PHI", 22],
  ["Tee Higgins", "WR", "CIN", 23],
  ["Travis Kelce", "TE", "KC", 24],
  ["DK Metcalf", "WR", "SEA", 25],
  ["David Njoku", "TE", "CLE", 26],
  ["Kyren Williams", "RB", "LAR", 27],
  ["Patrick Mahomes", "QB", "KC", 28],
  ["Garrett Wilson", "WR", "NYJ", 29],
  ["Trey McBride", "TE", "ARI", 30],
  ["Josh Jacobs", "RB", "GB", 31],
  ["Jaylen Waddle", "WR", "MIA", 32],
  ["D.J. Moore", "WR", "CHI", 33],
  ["James Cook", "RB", "BUF", 34],
  ["Jordan Addison", "WR", "MIN", 35],
  ["Mike Evans", "WR", "TB", 36],
  ["Deebo Samuel", "WR", "SF", 37],
  ["Kenneth Walker III", "RB", "SEA", 38],
  ["George Pickens", "WR", "PIT", 39],
  ["Sam LaPorta", "TE", "DET", 40],
  ["Jayden Daniels", "QB", "WAS", 41],
  ["Zay Flowers", "WR", "BAL", 42],
  ["Jaxon Smith-Njigba", "WR", "SEA", 43],
  ["Terry McLaurin", "WR", "WAS", 44],
  ["Ladd McConkey", "WR", "LAC", 45],
  ["Rico Dowdle", "RB", "DAL", 46],
  ["Joe Burrow", "QB", "CIN", 47],
  ["DeVonta Smith", "WR", "PHI", 48],
  ["Tank Dell", "WR", "HOU", 49],
  ["Jayden Reed", "WR", "GB", 50],
  ["Chris Olave", "WR", "NO", 51],
  ["Keon Coleman", "WR", "BUF", 52],
  ["Aaron Jones", "RB", "MIN", 53],
  ["Alvin Kamara", "RB", "NO", 54],
  ["Chase Brown", "RB", "CIN", 55],
  ["Najee Harris", "RB", "PIT", 56],
  ["Courtland Sutton", "WR", "DEN", 57],
  ["C.J. Stroud", "QB", "HOU", 58],
  ["Isiah Pacheco", "RB", "KC", 59],
  ["Chuba Hubbard", "RB", "CAR", 60],
  ["Marvin Harrison Jr.", "WR", "ARI", 61],
  ["Xavier Worthy", "WR", "KC", 62],
  ["Dalton Kincaid", "TE", "BUF", 63],
  ["Travis Etienne Jr.", "RB", "JAX", 64],
  ["Darnell Mooney", "WR", "ATL", 65],
  ["James Conner", "RB", "ARI", 66],
  ["Josh Downs", "WR", "IND", 67],
  ["Caleb Williams", "QB", "CHI", 68],
  ["Rhamondre Stevenson", "RB", "NE", 69],
  ["Romeo Doubs", "WR", "GB", 70],
  ["David Montgomery", "RB", "DET", 71],
  ["Rashee Rice", "WR", "KC", 72],
  ["Javonte Williams", "RB", "DEN", 73],
  ["Nick Chubb", "RB", "CLE", 74],
  ["Jake Ferguson", "TE", "DAL", 75],
  ["Mark Andrews", "TE", "BAL", 76],
  ["George Kittle", "TE", "SF", 77],
  ["Christian Kirk", "WR", "JAX", 78],
  ["Evan Engram", "TE", "JAX", 79],
  ["Amari Cooper", "WR", "BUF", 80],
  ["Quentin Johnston", "WR", "LAC", 81],
  ["Tony Pollard", "RB", "TEN", 82],
  ["Kyler Murray", "QB", "ARI", 83],
  ["Brian Robinson Jr.", "RB", "WAS", 84],
  ["Anthony Richardson", "QB", "IND", 85],
  ["Cooper Kupp", "WR", "LAR", 86],
  ["Michael Pittman Jr.", "WR", "IND", 87],
  ["Wan'Dale Robinson", "WR", "NYG", 88],
  ["Chris Godwin", "WR", "TB", 89],
  ["Pat Freiermuth", "TE", "PIT", 90],
  ["Tyler Lockett", "WR", "SEA", 91],
  ["Rashid Shaheed", "WR", "NO", 92],
  ["Diontae Johnson", "WR", "HOU", 93],
  ["Christian Watson", "WR", "GB", 94],
  ["Zack Moss", "RB", "CIN", 95],
  ["Adam Thielen", "WR", "CAR", 96],
  ["D'Andre Swift", "RB", "CHI", 97],
  ["Rome Odunze", "WR", "CHI", 98],
  ["Jeremiyah Love", "RB", "GB", 99],
  ["Jonathon Brooks", "RB", "CAR", 100],
  ["Carnell Tate", "WR", "CIN", 101],
  ["Jordyn Tyson", "WR", "ARI", 102],
  ["Makai Lemon", "WR", "JAX", 103],
  ["KC Concepcion", "WR", "IND", 104],
  ["Calvin Ridley", "WR", "TEN", 105],
  ["Davante Adams", "WR", "NYJ", 106],
  ["Jadarian Price", "RB", "NYG", 107],
  ["Devin Singletary", "RB", "NYG", 108],
  ["Tyler Allgeier", "RB", "ATL", 109],
  ["Joe Mixon", "RB", "HOU", 110],
  ["Zamir White", "RB", "LV", 111],
  ["Jonah Coleman", "RB", "ARI", 112],
  ["Denzel Boston", "WR", "NYJ", 113],
  ["Antonio Williams", "WR", "PIT", 114],
  ["Omar Cooper Jr.", "WR", "LAR", 115],
  ["T.J. Hockenson", "TE", "MIN", 116],
  ["Dallas Goedert", "TE", "PHI", 117],
  ["Dak Prescott", "QB", "DAL", 118],
  ["Jerome Ford", "RB", "CLE", 119],
  ["Emmett Johnson", "RB", "LAR", 120],
];

export default api({
  name: "SeedHistoricalAdp",
  description: "Seeds historical ADP data for 2024-25 and 2025-26 seasons.",

  integrations: {
    apps_db: postgres(APPS_DB),
  },

  input: z.object({}),

  output: z.object({
    message: z.string(),
  }),

  async run(ctx) {
    // Clear existing ADP data
    await ctx.integrations.apps_db.execute(
      `DELETE FROM ffwr_historical_adp WHERE season IN ('2024-25', '2025-26')`,
      undefined,
      { label: "Clear existing ADP data" }
    );

    // Insert 2024-25 ADP data in batches
    const batchSize = 30;
    for (let i = 0; i < ADP_2024.length; i += batchSize) {
      const batch = ADP_2024.slice(i, i + batchSize);
      const values = batch
        .map((_, idx) => `('2024-25', $${idx * 4 + 1}, $${idx * 4 + 2}, $${idx * 4 + 3}, $${idx * 4 + 4})`)
        .join(", ");
      const params = batch.flatMap(([name, pos, team, rank]) => [name, pos, team, rank]);

      await ctx.integrations.apps_db.execute(
        `INSERT INTO ffwr_historical_adp (season, player_name, position, nfl_team, adp_rank) VALUES ${values}`,
        params,
        { label: `Insert 2024-25 ADP batch ${Math.floor(i / batchSize) + 1}` }
      );
    }

    // Insert 2025-26 ADP data in batches
    for (let i = 0; i < ADP_2025.length; i += batchSize) {
      const batch = ADP_2025.slice(i, i + batchSize);
      const values = batch
        .map((_, idx) => `('2025-26', $${idx * 4 + 1}, $${idx * 4 + 2}, $${idx * 4 + 3}, $${idx * 4 + 4})`)
        .join(", ");
      const params = batch.flatMap(([name, pos, team, rank]) => [name, pos, team, rank]);

      await ctx.integrations.apps_db.execute(
        `INSERT INTO ffwr_historical_adp (season, player_name, position, nfl_team, adp_rank) VALUES ${values}`,
        params,
        { label: `Insert 2025-26 ADP batch ${Math.floor(i / batchSize) + 1}` }
      );
    }

    return { message: `Seeded ${ADP_2024.length} players for 2024-25 and ${ADP_2025.length} players for 2025-26.` };
  },
});
